### ISSUE TITLE
No JSON object error in test.py

### ISSUE THREAD

**Issue by ehsanmok** [Lynten/stanford-corenlp#1]
Hi

When I ran the test with python 2.7, I got the following error:

```
Initializing native server...
java -Xmx4g -cp "/home/ehsan/Java/JavaLibraries/stanford-corenlp-full-2016-10-31/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000
The server is available.
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print('Tokenize:', nlp.word_tokenize(sentence))
  File "/home/ehsan/Python/stanford-corenlp/stanfordcorenlp/corenlp.py", line 78, in word_tokenize
    r_dict = self._request('ssplit,tokenize', sentence)
  File "/home/ehsan/Python/stanford-corenlp/stanfordcorenlp/corenlp.py", line 114, in _request
    r_dict = json.loads(r.text)
  File "/home/ehsan/anaconda3/envs/py27-test-corenlp/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/ehsan/anaconda3/envs/py27-test-corenlp/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ehsan/anaconda3/envs/py27-test-corenlp/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by Lynten** [comment]
Which version of operating system do you use? You can set nlp = StanfordCoreNLP("path_to_corenlp", quiet=False) to print out what is going on.

**Comment by ehsanmok** [comment]
I'm on Ubuntu 14.04. That resulted to `Error: Could not find or load main class edu.stanford.r` after `The server is available`.

**Comment by ehsanmok** [comment]
Btw what the use case of creating another pywrapper https://github.com/brendano/stanford_corenlp_pywrapper ?

**Comment by Lynten** [comment]
I have tested the code on Ubuntu 14.04.5 with Oracle Java 1.8.0_131 and Python 2.7.6, and it works fine. 
Maybe you can  add a `print ` statement in the `corenlp.py`  file to see what the server has returned. And I guess the reason for this problem is  probably the files have been corrupted.

**Comment by Lynten** [comment]
Do you mean why I create another pywrapper since there is already one?

**Comment by matsair** [comment]
I have a similar issue.

```
Using an existing server http://localhost:9001
The server is available.
Named Entities:Traceback (most recent call last):
  File "/Users/werki001/Dev/corenlp-python/main.py", line 7, in <module>
    print 'Named Entities:', nlp.ner(sentence)
  File "/Users/werki001/Dev/corenlp-python/venv/lib/python2.7/site-packages/stanfordcorenlp/corenlp.py", line 87, in ner
    r_dict = self._request('ner', sentence)
  File "/Users/werki001/Dev/corenlp-python/venv/lib/python2.7/site-packages/stanfordcorenlp/corenlp.py", line 109, in _request
    r_dict = json.loads(r.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Exception AttributeError: "StanfordCoreNLP instance has no attribute 'p'" in <bound method StanfordCoreNLP.__del__ of <stanfordcorenlp.corenlp.StanfordCoreNLP instance at 0x10b994ef0>> ignored
```

Using MacOS 10.11.6 with virtualenv (Python 2.7.10), Java 1.8.0_77.
I ran the server manually using: `java -Xmx4g -cp "stanford-corenlp-full-2016-10-31/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9001`

Running the server using the simple usage example resulted in:
```
Initializing native server...
java -Xmx4g -cp "stanford-corenlp-full-2016-10-31*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000
Waiting until the server is available.
Waiting until the server is available.
Waiting until the server is available.
Waiting until the server is available.
Waiting until the server is available.
Waiting until the server is available.
Waiting until the server is available.
Waiting until the server is available.
Waiting until the server is available.
Waiting until the server is available.
Waiting until the server is available.
Waiting until the server is available.
Waiting until the server is available.
Waiting until the server is available.
```

**Comment by Lynten** [comment]
I have just released the version 3.7.0.2, have a try.

**Comment by matsair** [comment]
My error is gone. Pretty sure the reason was due to a bad connection to the CoreNLP Server, in my case most probably my corporate proxy.

**Comment by kn1ghtted** [comment]
This error still exists on my end. Seems to pertaining to specific "sentence" argument (it's working on some inputs but not on others)

Traceback (most recent call last):
  File "./noun_counter.py", line 117, in <module>
    NC.tag_contents()
  File "./noun_counter.py", line 87, in tag_contents
    tagged_strings = sNLP.pos(text)
  File "./noun_counter.py", line 24, in pos
    return self.nlp.pos_tag(sentence)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/stanfordcorenlp/corenlp.py", line 185, in pos_tag
    r_dict = self._request('pos', sentence)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/stanfordcorenlp/corenlp.py", line 228, in _request
    r_dict = json.loads(r.text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")

**Comment by chenwi** [comment]
I have the seem error.

`sentence = "Saturation and competition studies in the presence or absence of the histamine H1 receptor antagonist, levocabastine, revealed that [3H]SR 142948A bound with similar affinities to both the levocabastine-insensitive neurotensin NT1 receptors (20% of the total binding population) and the recently cloned <e1>levocabastine</e1>-sensitive <e2>neurotensin NT2 receptors</e2> (80% of the receptors) (Kd = 6.8 and 4.8 nM, respectively)."

with StanfordCoreNLP(r'D:\stanford-corenlp-full-2018-02-27') as nlp:
    print('Constituency Parsing:', nlp.parse(sentence))
    print('Dependency Parsing:', nlp.dependency_parse(sentence))`

Then it run some error.
Traceback (most recent call last):
  File "D:/Python_work/biorelation_extraction/script/pos_tag.py", line 17, in <module>
    print('Constituency Parsing:', nlp.parse(sentence))
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\stanfordcorenlp\corenlp.py", line 205, in parse
    r_dict = self._request('pos,parse', sentence)
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\stanfordcorenlp\corenlp.py", line 239, in _request
    r_dict = json.loads(r.text)
  File "D:\Anaconda3\envs\tensorflow\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda3\envs\tensorflow\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda3\envs\tensorflow\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
